name: Deploy to Itch.io

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.4
  EXPORT_NAME: loop-rama
  ITCH_PROJECT_NAME: loop-rama # Change this to your actual itch.io project name
  ITCH_USERNAME: cristiadu # Change this to your itch.io username

jobs:
  export-game:
    name: Export and Deploy
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      
      - name: Create export directory
        run: mkdir -v -p build
      
      - name: Create export presets
        run: |
          cat > export_presets.cfg << 'EOF'
          [preset.0]

          name="Web"
          platform="Web"
          runnable=true
          dedicated_server=false
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path="build/web/index.html"
          encryption_include_filters=""
          encryption_exclude_filters=""
          encrypt_pck=false
          encrypt_directory=false
          
          [preset.0.options]
          
          custom_template/debug=""
          custom_template/release=""
          variant/extensions_support=false
          vram_texture_compression/for_desktop=true
          vram_texture_compression/for_mobile=false
          html/export_icon=true
          html/custom_html_shell=""
          html/head_include=""
          html/canvas_resize_policy=2
          html/focus_canvas_on_start=true
          html/experimental_virtual_keyboard=false
          progressive_web_app/enabled=false
          progressive_web_app/offline_page=""
          progressive_web_app/display=1
          progressive_web_app/orientation=0
          progressive_web_app/icon_144x144=""
          progressive_web_app/icon_180x180=""
          progressive_web_app/icon_512x512=""
          progressive_web_app/background_color=Color(0, 0, 0, 1)

          [preset.1]

          name="Windows Desktop"
          platform="Windows Desktop"
          runnable=true
          dedicated_server=false
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path="build/windows/loop-rama.exe"
          encryption_include_filters=""
          encryption_exclude_filters=""
          encrypt_pck=false
          encrypt_directory=false
          
          [preset.1.options]
          
          custom_template/debug=""
          custom_template/release=""
          debug/export_console_wrapper=1
          binary_format/embed_pck=false
          texture_format/bptc=true
          texture_format/s3tc=true
          texture_format/etc=false
          texture_format/etc2=false
          binary_format/architecture="x86_64"
          codesign/enable=false
          codesign/identity=""
          codesign/password=""
          codesign/timestamp=true
          codesign/timestamp_server_url=""
          codesign/digest_algorithm=1
          codesign/description=""
          codesign/custom_options=PackedStringArray()
          application/modify_resources=true
          application/icon=""
          application/console_wrapper_icon=""
          application/icon_interpolation=4
          application/file_version=""
          application/product_version=""
          application/company_name=""
          application/product_name=""
          application/file_description=""
          application/copyright=""
          application/trademarks=""
          application/export_angle=0

          [preset.2]

          name="Linux/X11"
          platform="Linux/X11"
          runnable=true
          dedicated_server=false
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path="build/linux/loop-rama.x86_64"
          encryption_include_filters=""
          encryption_exclude_filters=""
          encrypt_pck=false
          encrypt_directory=false
          
          [preset.2.options]
          
          custom_template/debug=""
          custom_template/release=""
          debug/export_console_wrapper=1
          binary_format/embed_pck=false
          texture_format/bptc=true
          texture_format/s3tc=true
          texture_format/etc=false
          texture_format/etc2=false
          binary_format/architecture="x86_64"

          [preset.3]

          name="macOS"
          platform="macOS"
          runnable=true
          dedicated_server=false
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path="build/mac/loop-rama.zip"
          encryption_include_filters=""
          encryption_exclude_filters=""
          encrypt_pck=false
          encrypt_directory=false
          
          [preset.3.options]
          
          binary_format/architecture="universal"
          custom_template/debug=""
          custom_template/release=""
          debug/export_console_wrapper=1
          application/icon=""
          application/icon_interpolation=4
          application/bundle_identifier=""
          application/signature=""
          application/app_category="Games"
          application/short_version="1.0"
          application/version="1.0"
          application/copyright=""
          application/copyright_localized={}
          application/min_macos_version="10.12"
          display/high_res=true
          xcode/platform_build="14C18"
          xcode/sdk_version="13.1"
          xcode/sdk_name="macosx13.1"
          xcode/sdk_build="22C55"
          xcode/xcode_version="1420"
          xcode/xcode_build="14C18"
          codesign/codesign=1
          codesign/identity=""
          codesign/certificate_file=""
          codesign/certificate_password=""
          codesign/entitlements/custom_file=""
          codesign/entitlements/allow_jit_code_execution=false
          codesign/entitlements/allow_unsigned_executable_memory=false
          codesign/entitlements/allow_dyld_environment_variables=false
          codesign/entitlements/disable_library_validation=false
          codesign/entitlements/audio_input=false
          codesign/entitlements/camera=false
          codesign/entitlements/location=false
          codesign/entitlements/address_book=false
          codesign/entitlements/calendars=false
          codesign/entitlements/photos_library=false
          codesign/entitlements/apple_events=false
          codesign/entitlements/debugging=false
          codesign/entitlements/app_sandbox/enabled=false
          codesign/entitlements/app_sandbox/network_server=false
          codesign/entitlements/app_sandbox/network_client=false
          codesign/entitlements/app_sandbox/device_usb=false
          codesign/entitlements/app_sandbox/device_bluetooth=false
          codesign/entitlements/app_sandbox/files_downloads=0
          codesign/entitlements/app_sandbox/files_pictures=0
          codesign/entitlements/app_sandbox/files_music=0
          codesign/entitlements/app_sandbox/files_movies=0
          codesign/entitlements/app_sandbox/helper_executables=[]
          notarization/notarization=0
          notarization/apple_id_name=""
          notarization/apple_id_password=""
          notarization/apple_team_id=""
          texture_format/s3tc=true
          texture_format/etc=false
          texture_format/etc2=false
          EOF

      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless --verbose --export-release "Web" build/web/index.html

      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot --headless --verbose --export-release "Windows Desktop" build/windows/loop-rama.exe

      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot --headless --verbose --export-release "Linux/X11" build/linux/loop-rama.x86_64

      - name: macOS Build
        run: |
          mkdir -v -p build/mac
          godot --headless --verbose --export-release "macOS" build/mac/loop-rama.zip

      - name: Install Butler (itch.io CLI)
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Upload to itch.io (Web)
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
        run: |
          ./butler push build/web ${{ env.ITCH_USERNAME }}/${{ env.ITCH_PROJECT_NAME }}:web

      - name: Upload to itch.io (Windows)
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
        run: |
          ./butler push build/windows ${{ env.ITCH_USERNAME }}/${{ env.ITCH_PROJECT_NAME }}:windows

      - name: Upload to itch.io (Linux)
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
        run: |
          ./butler push build/linux ${{ env.ITCH_USERNAME }}/${{ env.ITCH_PROJECT_NAME }}:linux

      - name: Upload to itch.io (macOS)
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
        run: |
          ./butler push build/mac ${{ env.ITCH_USERNAME }}/${{ env.ITCH_PROJECT_NAME }}:mac